### ISSUE TITLE
libzmq abort() causes program termination without much useful information

### ISSUE THREAD

**Issue by jordansissel** [zeromq/jzmq#4]
Debugging java programs with gdb is funky and annoying at best. In complex programs it's often very hard to take a corefile created by abort() and correlate it with the offending line of code in the JVM.

Can we get jzmq to capture abort() from libzmq and emitting a java stack trace before crashing? This would very much help debugging issues similar to this one (http://github.com/zeromq/zeromq2/issues#issue/30).

**Comment by greggwon** [comment]
Overall ZeroMq use of abort is a clear example of broken software architecture.  If you've written network software or even serial communications software, you've learned that you can never control what happens on the other end of the connection.  Across the board, zeromq should just return error codes.  The software system using ZeroMQ should be able to choose how to handle the error that occurs.   ZeroMQ is used in multi thread environments and killing the whole process just because one thread of execution has problem is just not the answer.
