### ISSUE TITLE
Can't package with `mvn package`

### ISSUE THREAD

**Issue by utgarda** [zeromq/jzmq#412]
Seems like `${session.executionRootDirectory}` isn't substituted with whatever it's meant to be.
`mvn package -Dmaven.test.skip=true`
...
```console
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.3:single (make-assembly) on project jzmq-jni: Failed to create assembly: Error adding file to archive: /home/build/jzmq/jzmq-jni/${session.executionRootDirectory}/jzmq-jni/src/main/c++/.libs/libjzmq.so isn't a file. -> [Help 1]
```

**Comment by msteinhoff** [comment]
I recently introduced `${session.executionRootDirectory}`, maybe a little explanation is helpful to resolve this:

jzmq-core has a maven dependency on jzmq-jni because the jni module provides the Java API for libzmq. jzmq-jni itself needs the native java library stuff in `java.library.path`. Unfortunately, `java.library.path` is not managed by Maven classpath dependencies so there is some moderate magic going on with OS-dependent maven properties (`java.native.*`) and `java.library.path` is set on the command line for all maven tests.

So for the tests in jzmq-core to run successfully jzmq-core needs the path to a file somewhere in jzmq-jni.

I wanted to avoid juggling with relative paths in all the pom files, so I use `${session.executionRootDirectory}` which should give the absolute path to the root project but it seems I broke something in the assembly plugin while splitting the code into multiple modules.

**Comment by RamakrishnaAddanki** [comment]
Same issue I am facing too 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.3:single (make-assembly) on project jzmq-jni: Failed to create assembly: Error adding file to archive: /usr/lib/jzmq/jzmq-jni/${session.executionRootDirectory}/jzmq-jni/src/main/c++/.libs/libjzmq.so isn't a file.
