### ISSUE TITLE
Can i use Jzmq  3.1.0 to develop ZMTP 3.0 CurveZMQ mechanism 

### ISSUE THREAD

**Issue by RamakrishnaAddanki** [zeromq/jzmq#417]
I am currently working on  ZMTP3.0 CurveZMQ mechanism using jzmq libraries.so,i am having doubt that can i use jzmq-3.1.0 jar which is in maven central  to build that security mechanism in my application like using ZAP for Ldap authentication kind of things. or i need any new jar (like next release jars for that )

**Comment by msteinhoff** [comment]
I'd say its best to check out from master and install packages locally until we have a new maven release.

 #416  describes how to do this.

**Comment by RamakrishnaAddanki** [comment]
oh ok thanks for the reply. But problem is that i need official bindings (maven repo jar) to build that security on my platform bcoz platform is in distributed setup.my confusion is that jzmq3.1.0.jar also contains ZAuth and ZContext classes.so,is there any problem with that to implement security.have you got it ?

**Comment by msteinhoff** [comment]
When you talk about "official", does that mean some sort of policy within your organization that only allows jar files from maven central? Because this git repository is the official source and so are the local build artifacts that you create when you clone and build master as-is.

Do you want to make changes to the CurveZMQ mechanism or do you want to use the mechanism in your code? It seems that ZAuth, the class that implements the Java ZAP actor, currently does not handle the Curve mechanism, so I guess you want to make changes to that class. The [zauth implementation from czmq](https://github.com/zeromq/czmq/blob/master/src/zauth.c) and the RFC specs for ZAP and CurveZMQ should provide you with a good starting point.

**Comment by RamakrishnaAddanki** [comment]
Thank you very much for your reply.I want to use  CurveZMQ mechanism in my code to make zeromq connections secure for that i need to write code in java; and also i need to use LDAP via ZAP as an authenticator to handle the client request to zeromq server.so is this possible with old (jzmq-3.1.0.jar) or can i have to use the new master and build it. By using this master can i able to use curveZMQ mechanism in my code if not is there any other solution rather than implementing that zauth from czmq...

**Comment by msteinhoff** [comment]
The ZAuth implementation in jzmq currently does not implement the CURVE mechanism at all.
The zauth implementation in czmq works with a directory-based keystore.

For an LDAP backend you would have to create your own ZAuth actor anyway.

**Comment by RamakrishnaAddanki** [comment]
ok so with this master also i can't use curvezmq mechanism in my code right.we need to wait some more time for that...

**Comment by msteinhoff** [comment]
Correct, but feel free to send a PR to implement this feature.

See [C4.1](rfc.zeromq.org/spec:22) for more info about how to participate in jzmq development.

**Comment by msteinhoff** [comment]
@RamakrishnaAddanki If you don't plan to work on jzmq, could you please close the issue?

**Comment by RamakrishnaAddanki** [comment]
I am planning to work on JZMQ but it takes time i will get back ... Thank you for your support
